no	自动编号	自动编号
patient_id	文本	病人编号
patient_name	文本	病人姓名
patient_sex	文本	性别
patient_age	文本	病人年龄，数字后可带岁，小时，分钟，月，日等词。
patient_nation	文本	民族
patient_no	文本	病人住院号
patient_bedno	文本	病室号
patient_examineno	文本	门诊号
patient_seat	文本	病人孔位坐标，为区别同一个病人做几个相同的项目而设立A1..
check_no	文本	检测号
item_name	文本	检测项目名_第一通道
specimen_name	文本	标本名称
specimen_state	文本	标本状态
patient_clinic	文本	临床诊断
patient_type	文本	科室
result	文本	实验结果_第一通道
doctor_name	文本	送检医生
check_date	日期/时间	送检日期
reporter	文本	报告者
report_date	日期/时间	报告日期
reviser	文本	校正者
analysis_memo	文本	主要病历
value_BD	数字	本底值_第一通道
value_Cutoff	数字	Cutoff值_第一通道
value_Ct	数字	抬头循环数_第一通道
value_illno	数字	病原体数量_第一通道
value_consult	数字	参考值
value_cycle	备注	第一通道个循数的实测值，用分号分隔
value_standard	备注	第一通道X个标准品的值（illno,cycleBd)以分号分隔，中间以逗号分隔
Ct_aa	数字	画直线y=a+bx的参数a值
Ct_bb	数字	画直线y=a+bx的参数b值
patient_BodyCheckNo	文本	体检号
patient_SampleNo	文本	标本号
value_BD_F2	数字	本底值_第二通道
value_BD_F3	数字	本底值_第三通道
value_BD_F4	数字	本底值_第四通道
value_Cutoff_F2	数字	Cutoff值_第二通道
value_Cutoff_F3	数字	Cutoff值_第三通道
value_Cutoff_F4	数字	Cutoff值_第四通道
value_Ct_F2	数字	抬头循环数_第二通道
value_Ct_F3	数字	抬头循环数_第三通道
value_Ct_F4	数字	抬头循环数_第四通道
value_illno_F2	数字	病原体数量_第二通道
value_illno_F3	数字	病原体数量_第三通道
value_illno_F4	数字	病原体数量_第四通道
result_F2	文本	实验结果_第二通道
result_F3	文本	实验结果_第三通道
result_F4	文本	实验结果_第四通道
value_cycle_F2	备注	第二通道个循数的实测值，用分号分隔
value_cycle_F3	备注	第三通道个循数的实测值，用分号分隔
value_cycle_F4	备注	第四通道个循数的实测值，用分号分隔
item_name_F2	文本	检测项目名_第二通道
item_name_F3	文本	检测项目名_第三通道
item_name_F4	文本	检测项目名_第四通道
value_standard_F2	备注	第二通道X个标准品的值（illno,cycleBd)以分号分隔，中间以逗号分隔
value_standard_F3	备注	第三通道X个标准品的值（illno,cycleBd)以分号分隔，中间以逗号分隔
value_standard_F4	备注	第四通道X个标准品的值（illno,cycleBd)以分号分隔，中间以逗号分隔
